mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: powercrm_activity
  url: ${DATABASE_MYSQL_URL:mysql:3312}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
